name: graph
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6.0
  - numcodecs
  - pandas
  - pip
  - pyg=2.1.0=py310_torch_1.12.0_cu116
  - python=3.10.6
  - pytorch
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - scikit-learn
  - scipy
  - torchvision
  - tqdm
  - xarray
  - zarr
  - pip:
      - datasets
      - einops
      - fsspec
      - h3
      - torch-geometric-temporal
      - huggingface-hub
      - pysolar
      - pytorch-lightning
